import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Admin } from '../src/models/Admin.js';
import { Employee } from '../src/models/Employee.js';
import { Geofence } from '../src/models/Geofence.js';
import { Attendance } from '../src/models/Attendance.js';
import { Location } from '../src/models/Location.js';
import { Notification } from '../src/models/Notification.js';

dotenv.config();

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/employee_tracking');
    console.log('[Seeder] Connected to MongoDB...');

    // Clear existing collections
    await Admin.deleteMany({});
    await Employee.deleteMany({});
    await Geofence.deleteMany({});
    await Attendance.deleteMany({});
    await Location.deleteMany({});
    await Notification.deleteMany({});

    console.log('[Seeder] Cleared old dataset...');

    // 1. Create Default Admin
    const admin = await Admin.create({
      name: 'Corporate Chief Admin',
      email: 'admin@company.com',
      password: 'adminpassword123',
      role: 'superadmin',
      department: 'Executive Operations',
      phone: '+1 (555) 019-2834',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200'
    });

    console.log(`[Seeder] Admin Created: ${admin.email}`);

    // 2. Create Geofence
    const geofence = await Geofence.create({
      officeName: 'Corporate Tech HQ',
      latitude: 37.774929,
      longitude: -122.419416,
      radiusMeters: 200,
      officeWifiBSSIDs: [
        { ssid: 'Office_WiFi_Network', bssid: 'AA:BB:CC:DD:EE:01', minRssi: -85 },
        { ssid: 'Corp_Guest_5G', bssid: 'AA:BB:CC:DD:EE:02', minRssi: -85 }
      ],
      description: 'Main Silicon Valley Headquarters Geofence Perimeter',
      status: 'Active'
    });

    console.log(`[Seeder] Geofence Created: ${geofence.officeName}`);

    // 3. Create Sample Employees
    const employees = await Employee.create([
      {
        employeeId: 'EMP-1001',
        name: 'Alex Rivera',
        department: 'Engineering',
        designation: 'Senior IoT Architect',
        email: 'alex.rivera@company.com',
        phone: '+1 (555) 234-5678',
        deviceId: 'ESP32_EMP_1001',
        status: 'Active',
        currentStatus: 'Inside Office',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200'
      },
      {
        employeeId: 'EMP-1002',
        name: 'Sarah Chen',
        department: 'Operations',
        designation: 'Logistics Manager',
        email: 'sarah.chen@company.com',
        phone: '+1 (555) 345-6789',
        deviceId: 'ESP32_EMP_1002',
        status: 'Active',
        currentStatus: 'Outside Geofence',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200'
      },
      {
        employeeId: 'EMP-1003',
        name: 'Michael Vance',
        department: 'Hardware R&D',
        designation: 'Embedded Systems Lead',
        email: 'michael.vance@company.com',
        phone: '+1 (555) 456-7890',
        deviceId: 'ESP32_EMP_1003',
        status: 'Active',
        currentStatus: 'Inside Office',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200'
      },
      {
        employeeId: 'EMP-1004',
        name: 'Elena Rostova',
        department: 'Quality Assurance',
        designation: 'Field Test Specialist',
        email: 'elena.rostova@company.com',
        phone: '+1 (555) 567-8901',
        deviceId: 'ESP32_EMP_1004',
        status: 'Active',
        currentStatus: 'Outside Geofence',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200'
      }
    ]);

    console.log(`[Seeder] Seeded ${employees.length} Employees.`);

    // 4. Seed Initial Telemetry & Attendance
    const todayStr = new Date().toISOString().split('T')[0];
    for (const emp of employees) {
      await Location.create({
        employeeId: emp.employeeId,
        deviceId: emp.deviceId,
        latitude: 37.774929 + (Math.random() - 0.5) * 0.002,
        longitude: -122.419416 + (Math.random() - 0.5) * 0.002,
        speed: 1.2,
        satellites: 8,
        battery: 92,
        isInsideGeofence: emp.currentStatus === 'Inside Office',
        geofenceId: geofence._id,
        scannedWifi: [{ ssid: 'Office_WiFi_Network', bssid: 'AA:BB:CC:DD:EE:01', rssi: -62 }],
        verificationMethod: 'GPS'
      });

      await Attendance.create({
        employeeId: emp.employeeId,
        date: todayStr,
        checkInTime: new Date(Date.now() - 4 * 3600 * 1000),
        status: emp.currentStatus === 'Inside Office' ? 'Present' : 'Absent',
        workingHours: 4.0,
        autoGenerated: true
      });
    }

    console.log('[Seeder] Database Seeded Successfully!');
    process.exit(0);
  } catch (err) {
    console.error('[Seeder Error]:', err);
    process.exit(1);
  }
};

seedData();
