import { calculateHaversineDistance } from '../utils/haversine.js';
import { Geofence } from '../models/Geofence.js';
import { GeofenceLog } from '../models/GeofenceLog.js';
import { Employee } from '../models/Employee.js';
import { Attendance } from '../models/Attendance.js';
import { Notification } from '../models/Notification.js';
import { emitEvent } from '../config/socket.js';

export const processGeofenceEvaluation = async (employee, locationData) => {
  try {
    const activeGeofences = await Geofence.find({ status: 'Active' });
    let matchedGeofence = null;
    let isInside = false;
    let verificationMethod = 'OUTSIDE';
    let matchedRoom = null;

    // 1. Check GPS Haversine distance
    for (const geofence of activeGeofences) {
      const distanceMeters = calculateHaversineDistance(
        locationData.latitude,
        locationData.longitude,
        geofence.latitude,
        geofence.longitude
      );

      if (distanceMeters <= geofence.radiusMeters) {
        isInside = true;
        matchedGeofence = geofence;
        verificationMethod = 'GPS';
        break;
      }
    }

    // 2. Dual-Verification Fallback: Check scanned WiFi Access Point BSSIDs
    if (!isInside && locationData.scannedWifi && locationData.scannedWifi.length > 0) {
      for (const geofence of activeGeofences) {
        if (geofence.officeWifiBSSIDs && geofence.officeWifiBSSIDs.length > 0) {
          let foundAp = null;
          const match = locationData.scannedWifi.find(scanned => {
            foundAp = geofence.officeWifiBSSIDs.find(officeAp =>
              officeAp.bssid.toLowerCase() === scanned.bssid.toLowerCase() ||
              (officeAp.ssid && scanned.ssid && officeAp.ssid.toLowerCase() === scanned.ssid.toLowerCase())
            );
            return !!foundAp;
          });

          if (match && foundAp) {
            isInside = true;
            matchedGeofence = geofence;
            verificationMethod = 'WIFI_BSSID';
            matchedRoom = foundAp.roomName || null;
            break;
          }
        }
      }
    }

    const previousStatus = employee.currentStatus;
    const now = new Date();
    const todayStr = now.toISOString().split('T')[0]; // YYYY-MM-DD

    let eventTriggered = null;

    // Detect state changes
    const isPreviouslyInside = previousStatus && previousStatus.includes('Inside');

    if (isInside && !isPreviouslyInside) {
      // ENTRY EVENT
      eventTriggered = 'ENTRY';
      employee.currentStatus = matchedRoom ? `Inside ${matchedRoom}` : 'Inside Office';
      employee.lastSeen = now;
      await employee.save();

      // Log Event
      const log = await GeofenceLog.create({
        employeeId: employee.employeeId,
        deviceId: employee.deviceId,
        geofenceId: matchedGeofence._id,
        eventType: 'ENTRY',
        verificationMethod,
        latitude: locationData.latitude,
        longitude: locationData.longitude,
        timestamp: now
      });

      // Update / Create Attendance
      let attendance = await Attendance.findOne({ employeeId: employee.employeeId, date: todayStr });
      if (!attendance) {
        const isLate = now.getHours() >= 10; // Late if past 10 AM
        attendance = await Attendance.create({
          employeeId: employee.employeeId,
          date: todayStr,
          checkInTime: now,
          status: isLate ? 'Late' : 'Present',
          autoGenerated: true,
          geofenceEventsCount: 1
        });
      } else {
        if (!attendance.checkInTime) {
          attendance.checkInTime = now;
          attendance.status = 'Present';
        }
        attendance.geofenceEventsCount += 1;
        await attendance.save();
      }

      // Create Notification
      const notification = await Notification.create({
        title: `Employee Entry: ${employee.name}`,
        message: `${employee.name} (${employee.department}) entered ${matchedGeofence.officeName} via ${verificationMethod}.`,
        type: 'ENTRY',
        employeeId: employee.employeeId
      });

      // Emit Socket.IO Events
      emitEvent('geofence:entry', {
        employee,
        geofence: matchedGeofence,
        log,
        attendance,
        notification
      });

    } else if (!isInside && isPreviouslyInside) {
      // EXIT EVENT
      eventTriggered = 'EXIT';
      employee.currentStatus = 'Outside Geofence';
      employee.lastSeen = now;
      await employee.save();

      // Find last entry to calculate duration
      const lastEntryLog = await GeofenceLog.findOne({
        employeeId: employee.employeeId,
        eventType: 'ENTRY'
      }).sort({ timestamp: -1 });

      let durationMinutes = 0;
      if (lastEntryLog) {
        durationMinutes = Math.round((now.getTime() - new Date(lastEntryLog.timestamp).getTime()) / 60000);
      }

      // Log Exit Event
      const log = await GeofenceLog.create({
        employeeId: employee.employeeId,
        deviceId: employee.deviceId,
        geofenceId: matchedGeofence ? matchedGeofence._id : activeGeofences[0]?._id,
        eventType: 'EXIT',
        verificationMethod,
        latitude: locationData.latitude,
        longitude: locationData.longitude,
        durationMinutes,
        timestamp: now
      });

      // Update Attendance Check-Out & Working Hours
      let attendance = await Attendance.findOne({ employeeId: employee.employeeId, date: todayStr });
      if (attendance && attendance.checkInTime) {
        attendance.checkOutTime = now;
        const diffMs = now.getTime() - new Date(attendance.checkInTime).getTime();
        attendance.workingHours = Math.round((diffMs / (1000 * 60 * 60)) * 100) / 100;
        attendance.geofenceEventsCount += 1;
        await attendance.save();
      }

      // Create Notification
      const notification = await Notification.create({
        title: `Employee Exit: ${employee.name}`,
        message: `${employee.name} left office premises after staying ${durationMinutes} minutes.`,
        type: 'EXIT',
        employeeId: employee.employeeId
      });

      // Emit Socket.IO Events
      emitEvent('geofence:exit', {
        employee,
        log,
        attendance,
        notification
      });
    } else if (isInside && isPreviouslyInside) {
      // Still inside, but might have changed rooms
      const newStatus = matchedRoom ? `Inside ${matchedRoom}` : 'Inside Office';
      if (employee.currentStatus !== newStatus) {
        employee.currentStatus = newStatus;
        employee.lastSeen = now;
        await employee.save();
      }
    }

    // SOS Emergency Alert check
    if (locationData.sosAlert) {
      employee.currentStatus = 'SOS Alert';
      await employee.save();

      const sosNotification = await Notification.create({
        title: `🚨 SOS EMERGENCY ALERT: ${employee.name}`,
        message: `Emergency button activated by ${employee.name} at coordinates [${locationData.latitude}, ${locationData.longitude}].`,
        type: 'SOS_ALERT',
        employeeId: employee.employeeId
      });

      emitEvent('alert:sos', {
        employee,
        location: locationData,
        notification: sosNotification
      });
    }

    return {
      isInside,
      matchedGeofence,
      verificationMethod,
      eventTriggered,
      matchedRoom
    };

  } catch (error) {
    console.error('[Geofence Service Error]:', error);
    return { isInside: false, matchedGeofence: null, verificationMethod: 'GPS', eventTriggered: null, matchedRoom: null };
  }
};
