import { Attendance } from '../models/Attendance.js';
import { Employee } from '../models/Employee.js';

export const getDailyAttendance = async (req, res) => {
  try {
    const { date = new Date().toISOString().split('T')[0] } = req.query;

    const records = await Attendance.find({ date });
    const employees = await Employee.find({ status: 'Active' });

    // Combine employee details with attendance records
    const attendanceList = employees.map(emp => {
      const record = records.find(r => r.employeeId === emp.employeeId);
      return {
        employeeId: emp.employeeId,
        name: emp.name,
        department: emp.department,
        designation: emp.designation,
        avatar: emp.avatar,
        date,
        checkInTime: record?.checkInTime || null,
        checkOutTime: record?.checkOutTime || null,
        workingHours: record?.workingHours || 0,
        status: record ? record.status : 'Absent',
        autoGenerated: record ? record.autoGenerated : true
      };
    });

    res.json({ success: true, date, count: attendanceList.length, attendanceList });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export const getMonthlyAttendance = async (req, res) => {
  try {
    const { month, year } = req.query;
    const currentYear = year || new Date().getFullYear();
    const currentMonth = month ? String(month).padStart(2, '0') : String(new Date().getMonth() + 1).padStart(2, '0');
    const prefix = `${currentYear}-${currentMonth}`;

    const records = await Attendance.find({ date: { $regex: `^${prefix}` } });
    res.json({ success: true, month: prefix, count: records.length, records });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export const getAttendanceSummary = async (req, res) => {
  try {
    const todayStr = new Date().toISOString().split('T')[0];
    const totalEmployees = await Employee.countDocuments({ status: 'Active' });
    const todayRecords = await Attendance.find({ date: todayStr });

    const presentCount = todayRecords.filter(r => r.status === 'Present' || r.status === 'Late').length;
    const lateCount = todayRecords.filter(r => r.status === 'Late').length;
    const absentCount = totalEmployees - presentCount;
    const insideCount = await Employee.countDocuments({ currentStatus: 'Inside Office' });
    const outsideCount = await Employee.countDocuments({ currentStatus: 'Outside Geofence' });

    res.json({
      success: true,
      summary: {
        date: todayStr,
        totalEmployees,
        presentCount,
        lateCount,
        absentCount,
        insideCount,
        outsideCount,
        attendancePercentage: totalEmployees > 0 ? Math.round((presentCount / totalEmployees) * 100) : 0
      }
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export const manualCheckInOverride = async (req, res) => {
  try {
    const { employeeId, date, status, checkInTime, checkOutTime } = req.body;

    const targetDate = date || new Date().toISOString().split('T')[0];
    
    let record = await Attendance.findOne({ employeeId, date: targetDate });
    if (!record) {
      record = new Attendance({ employeeId, date: targetDate, autoGenerated: false });
    }

    if (checkOutTime) {
      record.checkOutTime = new Date(checkOutTime);
      if (record.checkInTime) {
        const diffMs = record.checkOutTime.getTime() - new Date(record.checkInTime).getTime();
        record.workingHours = Math.round((diffMs / (1000 * 60 * 60)) * 100) / 100;
      }
    }
    if (status) {
      record.status = status;
    }
    record.autoGenerated = false;
    await record.save();

    res.json({ success: true, message: 'Attendance record manually updated', record });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};
